# Generated by Django 3.2.8 on 2021-10-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transacoes'},
        ),
    ]
